language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'

before_script:
  - npm install -g grunt-cli karma-cli
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate < test/coverage/**/lcov.info

addons:
  code_climate:
    access_key: c50e76ff80b4c427f5901604967c567760d128efce1953369aebca859c118431
