language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g grunt-cli karma-cli
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate < test/coverage/**/lcov.info

install:
  - npm install
  - bower install

addons:
  code_climate:
    access_key: c50e76ff80b4c427f5901604967c567760d128efce1953369aebca859c118431
